### ISSUE TITLE
Prefixes and Suffixes Are Not Being Set

### ISSUE THREAD

**Issue by JTeigman** [DiFFoZ/PermissionExtensions#2]
I'm not sure if I'm doing something wrong, but I set the prefix and suffix (for testing purposes) to the same thing and nothing shows up in-game. The color does change though.
![image](https://user-images.githubusercontent.com/71998298/95119114-7432df80-0719-11eb-8cc9-671ce224a557.png)
I'm using the latest version of both OpenMod and PermissionExtensions.

**Comment by DiFFoZ** [comment]
Can you give me a log file?

**Comment by DiFFoZ** [comment]
I think is solved, so i will close it

**Comment by KillingCode** [comment]
i have the same issu
