### ISSUE TITLE
get no prefix 

### ISSUE THREAD

**Issue by KillingCode** [DiFFoZ/PermissionExtensions#5]
![image](https://github.com/EvolutionPlugins/PermissionExtensions/assets/140110183/b6cf3880-747a-4e7d-be5c-dfe0394a3ee9)

**Comment by KillingCode** [comment]
its outdate the plugin

**Comment by DiFFoZ** [comment]
Hi, can you check the `openmod.unturned.yaml` that `permissionSystem` is set to `OpenMod` or `Separate`

**Comment by KillingCode** [comment]
![image](https://github.com/EvolutionPlugins/PermissionExtensions/assets/140110183/62856fe9-84fe-485d-8065-b1c94f73d4bf)

that good right

**Comment by DiFFoZ** [comment]
I have made some changes, please try to update after 30 minutes and see if it's fixing the issue

**Comment by KillingCode** [comment]
thx it fix. thx a lot love u plugins. keep up te good work
