### ISSUE TITLE
prefix only i see it not the server ??

### ISSUE THREAD

**Issue by KillingCode** [DiFFoZ/PermissionExtensions#6]
I have a question the prefix can only see me and not other people from the server how do I fix that. so that everyone sees a rank in front of the name

![image](https://github.com/EvolutionPlugins/PermissionExtensions/assets/140110183/bd849734-a849-4137-a486-0e3e2b70383e)

**Comment by DiFFoZ** [comment]
For changing the name you will have to rejoin to the server, for chat it's not needed

**Comment by KillingCode** [comment]
is it hard to change it for the chat to see it. because there is no plugin that does that. been looking for 2 weeks now

**Comment by DiFFoZ** [comment]
This is because there's no server-to-client method to update nickname.
